using VRF to get random number & edit some functions
proud609/NFT_Enhancement pull request #1
Opened 2022-05-20 14:12 UTC by yuchen3890

- add variable upgradeFee, topLevel
- get random number from VRF
- check require
- edit some functions

2022-05-21 03:48 UTC, morris1961 requested changes

2022-05-21 03:48 UTC, morris1961 commented on contracts/Enhancement.sol
>      mapping(uint256 => uint8) tokenIdToLevel;
Please add public for me

2022-05-21 03:48 UTC, morris1961 commented on contracts/Enhancement.sol
> +    function getRandomNumber() public returns (bytes32 requestId) {
The function should be internal

2022-05-21 03:48 UTC, morris1961 commented on contracts/Enhancement.sol
> +    function fulfillRandomness(bytes32 requestId, uint256 randomness) internal override {
Don't know what the function for

2022-05-21 03:48 UTC, morris1961 commented on scripts/deploy.js
> +	.addParam("topLevel", "The highest level")
topLevel should default be 10

2022-05-21 04:02 UTC, yuchen3890 commented on contracts/Enhancement.sol
> +    function getRandomNumber() public returns (bytes32 requestId) {
Ok. Changed.

2022-05-21 04:03 UTC, yuchen3890 commented on scripts/deploy.js
> +	.addParam("topLevel", "The highest level")
Sorry. It's done now.

2022-05-21 04:03 UTC, yuchen3890 commented on contracts/Enhancement.sol
> +    function fulfillRandomness(bytes32 requestId, uint256 randomness) internal override {
I'll explain u later.

2022-05-22 04:11 UTC, morris1961 approved these changes
No problem please merge

2022-05-22 06:15 UTC, merged